### PR TITLE
specify header in more detail

### PR DESCRIPTION
**Pull request by azul**

### CODE REVIEW

**Comment by keks** [comment]
I'm not sure I like having only a URL to point to large keys. There should be at least one or two hashes of the actual key to make sure the correct key was retrieved.

**Comment by keks** [comment]
Also pinning the CA of the server might be a good idea

**Comment by keks** [comment]
I'm gonna bring all this up in an issue. Sorry for the noise.

**Comment by azul** [comment]
hi @keks, thanks for bringing the things up. We decided to not allow for urls or fingerprints at all. They can be put in the OpenPGP header and we try to be as simple as possible. Having the key ready to be used in the header means agents will not have to support means to fetch keys by fingerprint or url.

**Pull request merged**
